# Release configurations
[[releases.obsidian]]
file = "package.json"
mode = "replace"
key = "version"

[[releases.obsidian]]
file = "package-lock.json"
mode = "replace"
key = "version"

[[releases.obsidian]]
file = "manifest.json"
mode = "replace"
key = "version"

[[releases.obsidian]]
file = "versions.json"
mode = "append"
